# Generated by Django 3.2.3 on 2021-06-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userpage',
            fields=[
                ('userid', models.CharField(db_column='userID', max_length=20, primary_key=True, serialize=False)),
                ('useremail', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=30)),
                ('b_date', models.DateField()),
                ('user_phone', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userpage',
                'managed': False,
            },
        ),
    ]
