# Generated by Django 3.2.3 on 2021-07-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('a_code', models.CharField(db_collation='utf8mb4_0900_ai_ci', db_column='A_code', max_length=10)),
                ('userid', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=20, primary_key=True, serialize=False)),
                ('i_name', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=20)),
            ],
            options={
                'db_table': 'allergy',
                'managed': False,
            },
        ),
    ]
