# Generated by Django 3.2.3 on 2021-07-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banchan',
            fields=[
                ('banchan_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('banchan_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'banchan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredients_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ingredients_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ingredients',
                'managed': False,
            },
        ),
    ]
