# Generated by Django 3.2.3 on 2021-07-20 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanchanIngredients',
            fields=[
                ('b_code', models.OneToOneField(db_column='b_code', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mainpage.banchan')),
                ('i_name', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=20)),
            ],
            options={
                'db_table': 'banchan_ingredients',
                'managed': False,
            },
        ),
    ]
