# Generated by Django 3.2.3 on 2021-07-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userpage_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=45)),
                ('store_phone', models.IntegerField()),
                ('extra_address', models.CharField(blank=True, max_length=50, null=True)),
                ('address_detail', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.IntegerField()),
                ('adress', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'store',
                'managed': False,
            },
        ),
    ]
